CREATE TABLE public.orders (
	order_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	creation_date timestamptz(6) NULL,
	currency_code varchar(3) NULL,
	expiration_date timestamptz(6) NULL,
	status varchar(255) NULL,
	taxes_percentage numeric(38, 2) NULL,
	total_price_without_taxes numeric(38, 2) NULL,
	user_id int8 NOT NULL,
	CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE public.outbox_table (
	event_id varchar(255) NOT NULL,
	aggregate_id varchar(255) NULL,
	aggregate_type varchar(255) NULL,
	"data" bytea NULL,
	event_type varchar(255) NULL,
	"timestamp" timestamptz(6) NULL,
	CONSTRAINT outbox_table_pkey PRIMARY KEY (event_id)
);