#server:
#  port: 3801
spring:
  #  application:
  #    name: user-service-nixbuy
  #  datasource:
  #    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:3800/eureka
