apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-sa
  namespace: kube-logging
  labels:
    k8s-app: fluentd
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
