kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-clusterrolebiding
  namespace: kube-logging
  labels:
    k8s-app: fluentd
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: fluentd-sa
    namespace: kube-logging
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-clusterrole
  apiGroup: ""
