apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: kube-logging
  labels:
    app: fluentd
spec:
  selector:
    k8s-app: fluentd-logging
  ports:
    - protocol: TCP
      port: 24224
      targetPort: 24224
  type: ClusterIP
