apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: tunombreusuario/gateway-service-nixbuy:0.0.1-SNAPSHOT # Reemplaza con tu usuario de Docker Hub
          ports:
            - containerPort: <container-port> # Reemplaza con el puerto del contenedor
          resources:
            limits:
              memory: "360Mi"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: PORT
            - name: URI_USER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: URI_USER_SERVICE
            - name: URI_PRODUCTS_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: URI_PRODUCTS_SERVICE
            - name: URI_PAYMENT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: URI_PAYMENT_SERVICE
            - name: TRACING_URL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: TRACING_URL_ENDPOINT
