apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: <host-port> # Reemplaza con el puerto que expondrás en el host
      targetPort: <container-port> # Reemplaza con el puerto del contenedor
  type: NodePort # O ClusterIP si solo necesitas acceso dentro del clúster