apiVersion: v1
kind: Service
metadata:
  name: products-service-nixbuy
spec:
  selector:
    app: products-service-nixbuy-app
  ports:
    - protocol: TCP
      port: 3803 # Reemplaza con el puerto que expondrás en el host
      targetPort: 3803 # Reemplaza con el puerto del contenedor
  type: ClusterIP # Proporciona una dirección IP externa para acceder al servicio. En entornos de nube, esto generalmente aprovisiona un Load Balancer real.
