server:
  port: 3802

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:3800/eureka
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service-nixbuy
  cloud:
    gateway:
      routes:
        - id: user-service-nixbuy
          uri: lb://api/user-service-nixbuy
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

