server:
  port: 3804
CLIENT_URL: http://host.docker.internal:4200
spring:
  application:
    name: payment-service-nixbuy
  datasource:
    initialization-mode: always
    username: postgres
    url: jdbc:postgresql://host.docker.internal:5432/nixbuy_payments
    platform: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: true
    hibernate:
      ddl-auto: update


#feign:
#  httpclient:
#    enabled: false