type: object
properties:
  id:
    type: integer
    format: int64
    description: "Unique identifier of the product"
    example: 1
  name:
    type: string
    description: "Name of the product"
    example: "Sample Product"
  description:
    type: string
    description: "Description of the product"
    example: "This is a sample product description."
  urlImage:
    type: string
    format: uri
    description: "URL of the product image"
    example: "https://example.com/product-image.jpg"
  price:
    type: number
    format: float
    description: "Price of the product"
    example: 19.99