server:
  port: 3801
spring:
  application:
    name: user-service-nixbuy
  datasource:
    initialization-mode: always
    username: postgres
    url: jdbc:postgresql://localhost:5432/nixbuy_security
    platform: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: true
    hibernate:
      ddl-auto: update
#  profiles:
#    active: development
#  cloud:
#    config:
#      uri: http://localhost:8888
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
eureka:
  instance:
#    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      default-zone: http://localhost:8761/eureka/
