server:
  port: 3801
spring:
  application:
    name: user-service-nixbuy
  datasource:
    initialization-mode: always
    username: postgres
    url: jdbc:postgresql://localhost:5432/nixbuy_security
    platform: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: true
    hibernate:
      ddl-auto: update
#  profiles:
#    active: development
#  cloud:
#    config:
#      uri: http://localhost:8888
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:3800/eureka
