server:
  port: ${PORT:3805}

ISSUER_URI: http://localhost:3805
REDIRECT_URI: http://localhost:4200/callback

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: your-redis-password
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: auth-server
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            authorizationGrantType: authorization_code

PRIVATE_KEY_BASE64: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDGjo9ckChiMFNSSuEozvNjJeqV+xqk+e7yH+BTeJ0kYKsZGJku0iOM2hemKqdnri4MPlydGPQPY0Hb0RtxRrWq0o9NMFkYlHe2Ylg41ByZFcFSh/uQEjdizk/P29PMl+VzASyg5uzhLR1GYCxKwNpZKhiC5FrPYVJKeS4mqe15BjgX7RKMpEySwWMSi9ixJChDSPnaB0ldNzDOdEV8+g++9K8a2miFpxUZsG13HYPS762cejSZ8QfyWrG5TfXO8Q2B2BmzujUcp6fsSTqbC4NxT59IIx3/j7UwjLTLb11ZbRq1/ubTXB5a41GcYw2+ReWbxpkolhhoScyk2QkV+7gNAgMBAAECggEAGpC6TO0bVL/DIMXUnYF1fjTKz77lOrYXKnKUsIujoq6tqvw9NSQiY4Gjxl9QlIZGXOxUYc8T4EyBuZJJn1Hm6Rr7gfKlCQKG3cex/AXNFGJHwkNf/KT4n2dGYGNjUVfv9/9r5CnhVDiVVnQe7kV32+l47BJMtWWqUpJ8rT7w/yRXGKmJZjD4C2W0JDyGXf/MCdv3ok5lamZ971zAKI5Tijox980ObdbGisVZIae/Xd9E9R70qcrD/tv2+z+dA0VDcJhZKYW5cwErU9pgzXDn6+RwOHmmVxwxYWLj9RRAjm9HlXnwPByfMY5eWObOPVPTs6kWK536BdWyryo41qB21QKBgQDvmU3/doFJOAxy3Tu55+Wte3lMeTmzz67LeKhkZx+Omu+v4SkCLCF/kBFkAftAHk7nAqLnovfr14rsgRNPyMl8zqFQiqqql2uJuApRyMx6NOtZMPcqERPEspAqvZ/VkEdRW5SpZVPm7BGYNAhrvBJ7IaDvZLIWpDiBfbXYwJnxOwKBgQDUJgqy50a2f/VeKXqXrlmLDX37darl1Ai2SkNw5VDQPuC4W2xfsjGYfWkp2vGYGk8Ksare5MCDxWeiDT639qc1cAVTPdx851CzgHwptbD8sn+UFdAgj0yoJaap9NATiVl2fg7Jgrd9kO7TYlhNgvZ+KRN6n1LB+mtMoFyi+xRnVwKBgQCAQtYROlQNaRao6quNYol+LAoMGRz9l+DfhXDHhrjK8z/6LBNy2UL5cZsNqU3hzhe47J1eWMxVESaKYrJ+1GKgEFEkt4aTGcn0iHPlwhNMHEYckezONSQa+OfaKXaFsd2rvNXBNMAMbzUgAEK9wYk3JxJq9MGtAy5Ii44sQTZnfwKBgQCLU8SZBD0zpEvgIHur3Exgf2bq27d2I0/pcFJkdaYibfkl+pztKFlcHZkQbQNX8odQrahbpH4uzFmoWuyC4xGjjcNhjPIecchVax+gQPxQqWYSOlUq3RHqKHgRjH+PJRhFMrrBawDZDXNcDm2R0l3SM2XglXxDexQ3CeZs/1rCFwKBgQDSi1uh5e4VKmTvUA6SxAzxM9JTZhtAfOTHD1aZr7wksK4LO4S4Z3HuqZfhtgjs0isBEI/nkdfhzddIFuRW+wfmtXKSHtVE+59YfQT62PXQlrGT0rQ0gxgiTkq31fza4FLZ8bu0Udvd/8qnMa0QTl8T8N1GRV6viGbZwasOwVvoUw==
PUBLIC_KEY_BASE64: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxo6PXJAoYjBTUkrhKM7zYyXqlfsapPnu8h/gU3idJGCrGRiZLtIjjNoXpiqnZ64uDD5cnRj0D2NB29EbcUa1qtKPTTBZGJR3tmJYONQcmRXBUof7kBI3Ys5Pz9vTzJflcwEsoObs4S0dRmAsSsDaWSoYguRaz2FSSnkuJqnteQY4F+0SjKRMksFjEovYsSQoQ0j52gdJXTcwznRFfPoPvvSvGtpohacVGbBtdx2D0u+tnHo0mfEH8lqxuU31zvENgdgZs7o1HKen7Ek6mwuDcU+fSCMd/4+1MIy0y29dWW0atf7m01weWuNRnGMNvkXlm8aZKJYYaEnMpNkJFfu4DQIDAQAB

