openapi: 3.0.1
info:
  title: "User API"
  description: "API for managing users and token generation (probably refactored in future)"
  version: "1.0.0"

paths:
  /api/security/v1/authenticate:
    post:
      tags:
        - User Login
      summary: "Generate a new token"
      description: "Generate a new token with the given details."
      operationId: generateTokenV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserDto"
      responses:
        "200":
          description: "Product created successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthTokenDto"

components:
  schemas:
    LoginUserDto:
      $ref: "./schemas/LoginUserDto.yaml"
    AuthTokenDto:
      $ref: "./schemas/AuthTokenDto.yaml"