server:
  port: ${PORT:3802}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service-nixbuy
  cloud:
    gateway:
      routes:
        - id: user-service-nixbuy-route
#          uri: lb://user-service-nixbuy
          uri: ${URI_USER_SERVICE:http://host.docker.internal:3801}
          predicates:
            - Path=/api/user-service-nixbuy/**
          filters:
            - RewritePath=/api/user-service-nixbuy/(?<remaining>.*), /api/${remaining}
        - id: products-service-nixbuy-route
          uri: ${URI_PRODUCTS_SERVICE:http://host.docker.internal:3803}
          predicates:
            - Path=/api/products-service-nixbuy/**
          filters:
            - RewritePath=/api/products-service-nixbuy/(?<remaining>.*), /api/${remaining}
        - id: payment-service-nixbuy-route
          uri: ${URI_PAYMENT_SERVICE:http://host.docker.internal:3804}
          predicates:
            - Path=/api/payment-service-nixbuy/**
          filters:
            - RewritePath=/api/payment-service-nixbuy/(?<remaining>.*), /api/${remaining}
        - id: stripe-webhook-route
          uri: ${URI_PAYMENT_SERVICE:http://host.docker.internal:3804}
          predicates:
            - Path=/stripe/webhook
            #stripe listen --forward-to host.docker.internal:3802/stripe/webhook --skip-verify
tracing:
  url: ${TRACING_URL_ENDPOINT:http://host.docker.internal:4317}

management:
#  zipkin:
#    tracing:
#      endpoint: ${TRACING_URL_ENDPOINT:http://host.docker.internal:9411/api/v2/spans}
  # el sampling probability en 0.1 esta bien en un entorno de produccion
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true